#!/bin/bash

# Make sure we are in the right directory...

if [[ -d ./bin ]] && [[ -f ./bin/run.sh ]] && [[ -f ./bin/shell-tanks.sh ]]; then
	cd ./bin/
elif [[ -f run.sh ]] && [[ -f shell-tanks.sh ]]; then
	cd .
else
	echo "error, you need to at least be in the root of the repository"
	exit
fi

# See if we have some things installed...

if [[ ! -f warnings ]]; then
	echo 'mpwarn=false bcwarn=false bashvwarn=false' > warnings
fi

. warnings

if [[ ! $(which mplayer) ]] && [[ $mpwarn = true ]]; then
	echo "audio won't work unless you install mplayer"
	mpwarn=true
	read -s -n 1
else
	mpwarn=false
fi
if [[ ! $(which bc) ]] && [[ $bcwarn = true ]]; then
	echo "physics won't work unless you install bc, the game won't really be playable"
	bcwarn=true
	read -s -n 1
else
	bcwarn=false
fi
if [[ ! $(which bc) ]] && [[ $bcwarn = true ]]; then
	echo "physics won't work unless you install bc, the game won't really be playable"
	bcwarn=true
	read -s -n 1
else
	bcwarn=false
fi
echo 'mpwarn='$mpwarn' bcwarn='$bcwarn'' > warnings

# Run shell-tanks

bash run.sh "$@"
