#!/bin/bash

# Make sure we are in the right directory...

if [[ -d ./bin ]] && [[ -f ./bin/run.sh ]] && [[ -f ./bin/shell-tanks.sh ]]; then
	cd ./bin/
elif [[ -f run.sh ]] && [[ -f shell-tanks.sh ]]; then
	cd .
else
	echo "error, you need to at least be in the root of the repository"
	exit
fi

# Make sure we have some things installed...

if [[ ! $(which mplayer) ]]; then
	echo "audio won't work unless you install mplayer"
	read -s -n 1
fi
if [[ ! $(which bc) ]]; then
	echo "physics won't work unless you install bc, the game won't really be playable"
	read -s -n 1
fi

# Run shell-tanks

bash run.sh